# Generated by Django 4.2.5 on 2023-10-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_song_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
